name: Build KeyCastOW

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build KeyCastOW
        shell: cmd
        run: |
          msbuild keycastow.vcxproj /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143

      - name: Find EXE
        shell: powershell
        run: |
          Get-ChildItem -Path . -Recurse -Filter keycastow.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: KeyCastOW
          path: '**/keycastow.exe'
